In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import norm, det, inv, eig
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from scipy.linalg import lu, svd
from sklearn.preprocessing import StandardScaler

df=pd.read_csv('D:\Maths\student_scores_linear_algebra.csv',index_col=0)
df
X = df.values
print(X)

<>:9: SyntaxWarning: invalid escape sequence '\M'
<>:9: SyntaxWarning: invalid escape sequence '\M'
C:\Users\adity\AppData\Local\Temp\ipykernel_18292\594502053.py:9: SyntaxWarning: invalid escape sequence '\M'
  df=pd.read_csv('D:\Maths\student_scores_linear_algebra.csv',index_col=0)


[[78 51 53 65 54]
 [91 97 89 83 84]
 [68 61 97 73 40]
 [54 83 48 49 64]
 [82 64 65 75 46]
 [47 88 92 53 48]
 [60 66 41 70 63]
 [78 98 59 87 40]
 [97 81 67 54 83]
 [58 67 86 47 47]
 [62 99 99 53 63]
 [50 55 46 62 50]
 [50 54 83 99 90]
 [63 86 47 96 56]
 [92 90 86 79 47]
 [75 83 74 60 74]
 [79 94 53 55 74]
 [63 91 56 84 72]
 [42 96 75 57 98]
 [61 42 89 86 44]
 [92 76 79 92 81]
 [41 90 43 63 78]
 [63 46 41 65 97]
 [83 60 45 64 80]
 [69 48 93 99 67]
 [77 78 81 99 46]
 [41 57 43 99 48]
 [99 43 93 84 47]
 [60 64 68 80 51]
 [72 99 57 68 73]]


In [3]:
v1 = X[0]
v2 = X[1]

norm_1 = norm(v1, 1)
norm_2 = norm(v1, 2)

norm_1, norm_2

(np.float64(301.0), np.float64(136.51007288841362))

In [ ]:
dot_product = np.dot(v1, v2)
angle = np.arccos(dot_product / (norm(v1)*norm(v2))) * (180/np.pi)
dot_product, angle

(np.int64(26693), np.float64(10.528162978515226))

In [11]:
cross_product = np.cross(v1[:3], v2[:3])
cross_product

array([ -602, -2119,  2925])

In [7]:
projection = (np.dot(v1, v2) / np.dot(v2, v2)) * v2
projection

array([61.40820609, 65.4570988 , 60.05857518, 56.00968248, 56.68449793])

In [12]:
A = X[:5]
B = X[5:10]

matrix_addition = A + B
matrix_multiplication = np.dot(A, B.T)
matrix_addition, matrix_multiplication

(array([[125, 139, 145, 118, 102],
        [151, 163, 130, 153, 147],
        [146, 159, 156, 160,  80],
        [151, 164, 115, 103, 147],
        [140, 131, 151, 122,  93]]),
 array([[19067, 18171, 22024, 23240, 18092],
        [29432, 26613, 32436, 34101, 27280],
        [23277, 19713, 24956, 25298, 21684],
        [19927, 18148, 22001, 23135, 18132],
        [21649, 19957, 24868, 25361, 20321]]))

In [ ]:
square_matrix = X[:5, :5]

transpose = square_matrix.T
determinant = det(square_matrix)
inverse_matrix = inv(square_matrix)
transpose, determinant, inverse_matrix

(array([[78, 91, 68, 54, 82],
        [51, 97, 61, 83, 64],
        [53, 89, 97, 48, 65],
        [65, 83, 73, 49, 75],
        [54, 84, 40, 64, 46]]),
 np.float64(-408769.9999999631),
 array([[-3.33161436,  4.48811312, -2.06215231, -3.27817599,  2.06945715],
        [-0.81952687,  1.0394892 , -0.4854368 , -0.74041637,  0.51611909],
        [-1.02781515,  1.39300829, -0.61004966, -1.01585244,  0.60664922],
        [ 4.4943856 , -6.05391785,  2.75944908,  4.40049417, -2.74298505],
        [ 1.20372092, -1.54465837,  0.7143259 ,  1.13457446, -0.7703354 ]]))

In [14]:
cov_matrix = np.cov(X.T)
eigenvalues, eigenvectors = eig(cov_matrix)

eigenvalues, eigenvectors

(array([509.23760608, 399.89240722, 269.85008233, 201.41089681,
        223.08372021]),
 array([[-0.2817596 , -0.36660718, -0.61912224, -0.50432005, -0.38543434],
        [ 0.4231161 , -0.68496732,  0.16656353,  0.38058633, -0.42332395],
        [-0.59372624, -0.57384855,  0.19113876,  0.11892188,  0.51721422],
        [-0.41553138,  0.22251658, -0.39119112,  0.74735504, -0.25739074],
        [ 0.46519579, -0.13267686, -0.63196497,  0.16773001,  0.58178747]]))

In [15]:
P, L, U = lu(square_matrix)
P, L, U

(array([[0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.85714286,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.74725275,  0.35726496,  1.        ,  0.        ,  0.        ],
        [ 0.9010989 ,  0.72820513,  0.04531842,  1.        ,  0.        ],
        [ 0.59340659, -0.79145299, -0.5988285 ,  0.67896416,  1.        ]]),
 array([[ 91.        ,  97.        ,  89.        ,  83.        ,
          84.        ],
        [  0.        , -32.14285714, -23.28571429,  -6.14285714,
         -18.        ],
        [  0.        ,   0.        ,  38.81367521,  13.17264957,
         -16.33846154],
        [  0.        ,   0.        ,   0.        ,   4.08508764,
         -15.84418215],
        [  0.        ,   0.        ,   0.        ,   0.        ,
           0.88138773]]))

In [16]:
U_svd, S_svd, Vt_svd = svd(X)
U_svd, S_svd, Vt_svd

(array([[-1.56976245e-01, -7.00818994e-02,  1.08423632e-01,
         -4.83447353e-02, -2.36373256e-01,  1.08128433e-01,
         -1.78365493e-01, -7.64849135e-02, -3.42930680e-01,
         -4.37862712e-02,  3.72315190e-02, -1.20430098e-01,
         -1.47666090e-01, -9.17243238e-02, -1.56435146e-01,
         -1.70497168e-01, -1.92772830e-01, -9.60767657e-02,
          1.67051525e-02, -1.37271258e-01, -3.01086471e-01,
         -1.02637241e-02, -3.51803264e-01, -3.70296072e-01,
         -2.08646336e-01, -1.16991894e-01, -5.68902921e-02,
         -3.58083356e-01, -1.06180716e-01, -1.21840242e-01],
        [-2.31792102e-01,  4.98917890e-02, -6.77659301e-02,
         -7.11945576e-02, -6.42795854e-02, -2.96751963e-01,
         -1.03971846e-01, -2.13568244e-01,  7.09582171e-02,
         -8.00600050e-02, -2.66956109e-01, -8.63912728e-02,
         -1.04165423e-01, -2.46210618e-01, -4.71197745e-02,
         -9.21979721e-02, -1.41781380e-01, -2.60132829e-01,
         -3.89511655e-01,  6.12036676e-

In [17]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
X_pca

array([[ 0.34476463, -0.71118343],
       [ 0.12869407,  2.1539822 ],
       [ 1.59978406,  0.14408883],
       [-1.76599812, -0.45716833],
       [ 0.96255973, -0.04758829],
       [-0.41343835,  0.38556759],
       [-0.71484145, -1.20241697],
       [ 0.54534555,  0.49529639],
       [-0.81966118,  1.65761256],
       [-0.03229597,  0.05391644],
       [-0.63301221,  1.58690958],
       [-0.43857259, -1.79582179],
       [ 0.50324083, -0.96537309],
       [ 0.08127384, -0.70064677],
       [ 1.16121115,  1.61966344],
       [-0.68144474,  0.94010373],
       [-1.49750626,  0.94261856],
       [-0.67123735, -0.0280136 ],
       [-2.37892614,  0.40230021],
       [ 2.01456942, -1.02429815],
       [ 0.76810796,  1.15270973],
       [-2.23571093, -0.89434214],
       [-1.34024491, -1.34458419],
       [-0.71818108, -0.21611059],
       [ 1.89678901, -0.39737621],
       [ 1.70240625,  0.32089932],
       [ 0.53512966, -2.60800743],
       [ 2.67774159,  0.55494443],
       [ 0.62139304,

In [18]:
labels = (df.mean(axis=1) >= df.mean(axis=1).mean()).astype(int)

lda = LinearDiscriminantAnalysis(n_components=1)
X_lda = lda.fit_transform(X_scaled, labels)
X_lda

array([[-2.43479159],
       [ 4.55207426],
       [-0.92742393],
       [-2.05063269],
       [-0.82650648],
       [-1.06104057],
       [-1.9160972 ],
       [ 1.40448109],
       [ 1.31938039],
       [-2.53292308],
       [ 1.13252458],
       [-3.89940824],
       [ 1.18453581],
       [ 0.88467379],
       [ 2.1830602 ],
       [ 0.73567045],
       [ 0.61611781],
       [ 1.493335  ],
       [ 1.13337224],
       [-1.72931866],
       [ 3.33891676],
       [-0.85610962],
       [-1.8494573 ],
       [-0.83359201],
       [ 0.88556767],
       [ 1.78707385],
       [-2.14635957],
       [ 0.0209769 ],
       [-1.10679705],
       [ 1.49869719]])